import Head from 'next/head'

import { Inter } from '@next/font/google'
import { Canvas } from '@react-three/fiber'

import AnimatedBox from '@/component/AnimatedBox'





 

 
export default function Home() {
  
  return (
    <>
      <Head>
        <title>Meet me </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
      <Canvas>
        <ambientLight intensity={0.01} />
  <directionalLight color="blue" position={[0, 0, 5]} />
       <AnimatedBox/>
        </Canvas>
      </div>
        
    </>
  )
}
